version: '3.1'
services:
  RevProxy:
    image: haproxytech/haproxy-alpine:latest
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "85:85"
      - "81:81"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      purewood-net:
        ipv4_address: 172.28.0.2

  webapp:
    build:
      context: ../Frontend
      dockerfile: ../Frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "3010:3000"
    networks:
      purewood-net:
        ipv4_address: 172.28.0.3

  webapp1:
    build:
      context: ./../Frontend
      dockerfile: ./../Frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "3011:3000"
    networks:
      purewood-net:
        ipv4_address: 172.28.0.4


  api:
    build:
      context: ./../Api
      dockerfile: ./../Api/Dockerfile
    restart: always
    ports:
      - "3020:3000"
    env_file:
        - .env
    networks:
      purewood-net:
        ipv4_address: 172.28.0.5

  api2:
    build:
      context: ./../Api
      dockerfile: ./../Api/Dockerfile
    restart: always
    ports:
      - "3030:3000"
    env_file:
        - .env
    networks:
      purewood-net:
        ipv4_address: 172.28.0.6


  ai:
    image: python:latest
    restart: always
    ports:
      - "3040:3000"
    env_file:
      - .env
    volumes:
      - ./../AI
    networks:
      purewood-net:
        ipv4_address: 172.28.0.7

  ai2:
    image: python:latest
    restart: always
    ports:
      - "3050:3000"
    env_file:
      - .env
    volumes:
      - ./../AI
    networks:
      purewood-net:
        ipv4_address: 172.28.0.8


  bd:
    image: mysql:latest
    container_name: mysql-purewood
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      purewood-net:
        ipv4_address: 172.28.0.11


  bd2:
    image: mysql:latest
    container_name: mysql-purewood
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      purewood-net:
        ipv4_address: 172.28.0.12

networks:
  purewood-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/24"
